root: true
env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - codex/ts
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
ignorePatterns:
  - 'vite.config.ts'
  - 'src/vite-env.d.ts'
  - 'dist/**/*'
settings:
  react:
    version: detect
