name: ESLint Runner
on:
  - push

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

  lint:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - name: Run ESLint check
        run: yarn lint:ci
